---
title: "OA-microbiome"
author: "Li-Fang Yeo"
date: "21st Nov 2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
library(mia)
library(tidyverse)
library(dplyr)
library(knitr)
library(miaViz)
library(stringr)
library(maaslin3)
library(tableone)
library(ggsignif)
```
```{r}
#function to make my life easier
#This function works like dplyr::mutate
tse_mutate <- function(.data, ...) {
  dots <- rlang::enquos(...)
  new_data <-  tse_meta(.data) %>%
    dplyr::mutate(!!!dots) %>%
    tibble::column_to_rownames(var = "rownames") %>%
    S4Vectors::DataFrame()
  SummarizedExperiment::colData(.data) <- new_data
  .data
}
#this function is needed for tse_mutate to work
tse_meta <- function(x, rownames = TRUE) {
  { if (inherits(x, "TreeSummarizedExperiment")) SummarizedExperiment::colData(x) else x } %>%
    { if(rownames) tibble::as_tibble(., rownames = "rownames") else tibble::as_tibble(.) }
}
```

Data input 
```{r}
meta <- read.csv("Metafile.csv", row.names = 1, header = TRUE)
#meta <- meta %>% mutate(Group = str_replace_all(Group,"Temiar", "A"))
tse <- importMetaPhlAn("data/42_abund_fixed.txt", assay.type = "relabundance", col.data = meta, removeTaxaPrefixes = TRUE)
tse <- tse %>% tse_mutate(dplyr::across(c(Group.Bi), as.factor))
```
```{r}
myVars <- c("Age", "Systolic", "Diastolic", "BMI.1", "WaistCirc", "HbA1C.1",
          "H.pylori","Gender", "Smoke", "BMI", "HbA1C","Group")
## Vector of categorical variables that need transformation
catVars <- c("Gender", "Smoke", "BMI", "HbA1C","Group","H.pylori")
tableone <- CreateTableOne(vars= myVars, data = meta, strata = "Group", factorVars = catVars) 
tab <- print(tableone, quote = FALSE, noSpaces = TRUE, printToggle = FALSE)
write.csv(tab, "tableone.csv")
```

```{r}
#agglomerate data
x1 <- altExp(tse, "species")

my_colors <- c("Malay"="darkkhaki", "Temuan"="#8eb79c","Temiar"= "#4b705c","Jahai" = "black")

```
Alpha diversity 
```{r}
library(scater)
library(patchwork)
library(ggsignif)
x1 <- mia::addAlpha(x1, 
                              assay.type = "relabundance",
                              index = "shannon_diversity", 
                              name = "shannon")
df<- as.data.frame(colData(x1))
#change level
df$Group <- factor(df$Group, levels = c("Jahai", "Temiar", "Temuan", "Malay"))
# For significance testing, all different combinations are determined
comb <- split(t(combn(levels(df$Group), 2)), 
           seq(nrow(t(combn(levels(df$Group), 2)))))

p<- ggplot(df, aes(x = Group, y = shannon, fill = Group)) +
  # Outliers are removed, because otherwise each 
  # data point would be plotted twice; 
  # as an outlier of boxplot and as a point of dotplot.
  geom_boxplot(outlier.shape = NA) + 
  geom_jitter(width = 0.2) + 
  geom_signif(comparisons = comb, test = "wilcox.test", map_signif_level = FALSE,
              correction="fdr", step_increase = 0.1) + #Corrects the p-values and step increase minimise overlap
  theme(text = element_text(size = 6)) + theme_classic() +
  scale_fill_manual(values = my_colors)
ggsave("alpha.pdf",
       p, 
       width = 8,
       height = 6,
       units = "in")
```
Beta diversity
```{r}
x1 <- runRDA(x1,
               assay.type = "relabundance",
               formula = assay ~ Group + Reads,
               distance = "bray",
               na.action = na.exclude)

# Store results of PERMANOVA test
rda_info <- attr(reducedDim(x1, "RDA"), "significance")
```
```{r}
rda_info$permanova |>
  knitr::kable()

write.csv(rda_info$permanova, "permanova.csv")
```
```{r}
rda_info$homogeneity |>
  knitr::kable()

write.csv(rda_info$homogeneity, "homogeneity.csv")
```
```{r}
#dbRDA plot
p <- plotRDA(x1, "RDA", add.ellipse = TRUE, color_by = "Group") +
  scale_color_manual(values = my_colors, name = "Groups",
  breaks = c("Jahai", "Temiar", "Temuan", "Malay")) +
  theme_classic() 
ggsave("RDA.pdf",
       p, 
       width = 8,
       height = 6,
       units = "in")
```
```{r}
#plot dbRDA loadings
L <- miaViz::plotLoadings(x1, "RDA", ncomponents = 2, n = 10)

L<- L + scale_fill_manual(name = "Effect", 
                          values = c("blue", "maroon"),
                          labels = c('Negative', 'Positive'))

L
library(patchwork)
p / L
onni <- p / L
ggsave("RDA-loadings.pdf",
       onni, 
       width = 8,
       height = 8,
       units = "in")
```

Differential abundance analysis
```{r}
tse3 <- tse %>% 
  mia::agglomerateByRank(rank = "species") %>%
  mia::agglomerateByPrevalence(assay.type = "relabundance",
                               detection =  0.1/100,
                               prevalence = 5/100)
  

maaslin3_out <- maaslin3(
  input_data = tse3,
  output = "DAA_taxa",
  formula = " ~ Group + Reads",
  normalization = "CLR",
  transform = "NONE",
  verbosity = "ERROR",
  standardize = "TRUE",
  reference = "Group,Malay",
  warn_prevalence = "FALSE",
  max_significance = 0.05,
  correction = "BH",
  plot_summary_plot = TRUE,
  plot_associations = FALSE
)
```
## Predicted pathway analysis
```{r}
pw <- read_delim("data/subset_pathabundance-cpm.tsv", 
     delim = "\t", escape_double = FALSE, 
     trim_ws = TRUE)
```
Clean up
```{r}
colnames(pw) <- gsub("HFJYKBBXY_", "", colnames(pw))
colnames(pw) <- gsub("HHCNCBBXY_", "", colnames(pw))
colnames(pw) <- gsub("_.*", "", colnames(pw))
pw <- pw %>% rename("Pathway"  = "# Pathway")

#discrepancy between sampleID
pw <- pw %>% dplyr::rename(TM0123M = TM123M) %>%
            dplyr::rename(TM0167F = TM167F) %>%
            dplyr::rename(TM0169M = TM169M)
#Filter pathway abundance table first
abund_table <- pw %>% 
  filter(rowSums(across(where(is.numeric)))!=0) %>%
  #grep all Pathways that end with species
  filter(!grepl('.s__', Pathway)) %>%
  #remove all unintegrated pathways
  filter(!grepl('UNINTEGRATED|superpathway', Pathway))

#Preparing data format to fit tse
#list of pathways
row_data <- abund_table %>% dplyr::select(Pathway)
#give abundance table rowname
abund_table <- abund_table %>% tibble::column_to_rownames(var="Pathway")
#reordering to match
genomic_idx <- match(rownames(meta), colnames(abund_table))
genomic_idx
abund_reordered  <- abund_table[ , genomic_idx]
all(rownames(meta) == colnames(abund_reordered))
#pathway abundance table needs to be same order
pw1 <- as.matrix(abund_reordered)
#read in as tse
tse_func <- TreeSummarizedExperiment(assays = SimpleList(relabundance = pw1),
                                     colData = DataFrame(meta),
                                     rowData = DataFrame(row_data))

tse_func
```
subset for pathways that have at least 5% prevalence
```{r}
tse_test <- tse_func %>% subsetByPrevalent (assay.type = "relabundance",
          prevalence = 5/100)

```
Linear model for differential abundance in predicted pathways
```{r}
maaslin3_out <- maaslin3(
  input_data = tse_test,
  output = "Fun_DAA",
  formula = " ~ Group + Reads",
  normalization = "CLR",
  transform = "NONE",
  verbosity = "ERROR",
  standardize = "TRUE",
  reference = "Group,Malay",
  warn_prevalence = "FALSE",
  max_significance = 0.05,
  correction = "BH",
  plot_summary_plot = TRUE,
  plot_associations = FALSE
)
```
